# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e3699e894658b97e6c80638fa9f3f14"
name = "feedinsta"
handle = "feedinsta"
application_url = "https://flight-para-britannica-general.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quick-wishlist.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://flight-para-britannica-general.trycloudflare.com/auth/callback",
  "https://flight-para-britannica-general.trycloudflare.com/auth/shopify/callback",
  "https://flight-para-britannica-general.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
